#!/usr/bin/env node
// One definition of "this path is generated, vendored, or tool-owned — a hand edit to it is
// silently lost on the next build".
//
// Two callers share it, deliberately:
//
//   .claude/hooks/guard-write.mjs   Edit / Write / MultiEdit, which name a file directly
//   .claude/hooks/guard-bash.mjs    Bash, where the same write hides inside a shell command
//
// That mirrors check-push-target.mjs and scan-staged.mjs, and it exists for the same reason.
// guard-write only ever saw the `file_path` of an Edit or Write tool call, so `sed -i` into
// android/build.gradle, `echo > package-lock.json`, and `tee node_modules/x` all walked
// straight past it. Two copies of the path list would eventually disagree about what counts,
// so there is one copy, here.
//
// WHAT THIS CANNOT SEE, stated plainly so nobody trusts it further than it goes: a write
// performed inside a program rather than by the shell. `node -e "fs.writeFileSync(...)"`,
// `python -c`, a script that writes when run, or a path built from a variable are all
// invisible to a parser that reads the command line. This layer raises the cost of an
// accident; it is not a sandbox.

/** Paths nothing should hand-edit, with the reason a person needs to hear. */
export const PROTECTED = [
  {
    re: /(^|[\/\\])node_modules[\/\\]/,
    why: "installed by npm; edits vanish on the next install",
  },
  { re: /(^|[\/\\])\.expo[\/\\]/, why: "generated by the Expo CLI" },
  {
    re: /(^|[\/\\])(android|ios)[\/\\]/,
    why: "generated by prebuild; change app.json or a config plugin instead",
  },
  { re: /(^|[\/\\])(dist|build|coverage)[\/\\]/, why: "build output" },
  {
    re: /package-lock\.json$/,
    why: "regenerate it with 'npm install' rather than editing it by hand",
  },
  { re: /expo-env\.d\.ts$/, why: "generated by Expo" },
  { re: /(^|[\/\\])\.git[\/\\]/, why: "git internals" },
];

/**
 * The first protected-path rule a path trips, or null.
 *
 * @param {string} path
 * @returns {{re: RegExp, why: string}|null}
 */
export function violation(path) {
  if (!path) return null;
  return PROTECTED.find((rule) => rule.re.test(path)) ?? null;
}

/** The message both guards print, so the advice never drifts between them. */
export function refusal(path, why, how) {
  return (
    `Blocked write to a protected path — ${why}.\n  ${path}\n` +
    (how ? `${how}\n` : "") +
    `If this really is the right place to change, say so and a person can do it deliberately.\n`
  );
}

// ---------------------------------------------------------------- shell write parsing

/** Flags that swallow the token after them, so it is never mistaken for a file operand. */
const SED_TAKES_A_VALUE = new Set(["-e", "-f", "--expression", "--file"]);

/**
 * Split a command into tokens, respecting quotes.
 *
 * Quote-aware because the whole point is to read the operand as the shell would. A naive
 * split on whitespace turns `sed -i 's/a b/c/' file` into five tokens and loses which one
 * is the file.
 *
 * @param {string} segment
 * @returns {string[]}
 */
function tokenize(segment) {
  const tokens = [];
  let current = "";
  let quote = null;
  let started = false;

  for (const ch of segment) {
    if (quote) {
      if (ch === quote) quote = null;
      else current += ch;
      continue;
    }
    if (ch === "'" || ch === '"') {
      quote = ch;
      started = true;
      continue;
    }
    if (/\s/.test(ch)) {
      if (started || current) tokens.push(current);
      current = "";
      started = false;
      continue;
    }
    current += ch;
  }
  if (started || current) tokens.push(current);
  return tokens;
}

/** `>`, `>>`, `2>`, `&>` write a file. `>&1` and `2>&1` duplicate a descriptor — not a file. */
function redirectTargets(segment) {
  const found = [];
  // Capture the operand after a redirect, whether it is glued on (`>out`) or spaced (`> out`).
  const re = /(?:^|\s)(?:\d*|&)>{1,2}\s*([^\s;|&>]+)/g;
  let m;
  while ((m = re.exec(segment)) !== null) {
    const target = m[1];
    if (!target || target.startsWith("&")) continue; // fd duplication
    found.push(target);
  }
  return found;
}

/**
 * Which paths would this one shell command write to?
 *
 * Covers the ways a file actually gets rewritten in this repo's tooling: shell redirects,
 * `sed -i`, `tee`, the destination of `cp`/`mv`, `dd of=`, and `truncate`. Reads are
 * deliberately not flagged — `cat node_modules/x` and `grep -r dist` are fine, and a guard
 * that fires on them teaches people to work around it rather than with it.
 *
 * @param {string} segment  one command, already split off any && / ; chain
 * @returns {string[]} paths this command would write
 */
export function shellWriteTargets(segment) {
  if (!segment) return [];
  const targets = redirectTargets(segment);
  const tokens = tokenize(segment);
  if (tokens.length === 0) return targets;

  // Strip a leading `sudo` and any VAR=value prefixes so the verb is the first token.
  let i = 0;
  if (tokens[i] === "sudo") i++;
  while (i < tokens.length && /^[A-Za-z_][A-Za-z0-9_]*=/.test(tokens[i])) i++;
  const verb = (tokens[i] ?? "").split(/[\/\\]/).pop();
  const args = tokens.slice(i + 1);

  const operands = (skipValueFlags = new Set()) => {
    const out = [];
    for (let j = 0; j < args.length; j++) {
      const arg = args[j];
      if (arg.startsWith("-") && arg !== "-") {
        if (skipValueFlags.has(arg)) j++;
        continue;
      }
      out.push(arg);
    }
    return out;
  };

  switch (verb) {
    case "sed": {
      // In-place only. `sed 's/a/b/' file` writes to stdout and changes nothing on disk.
      const inPlace = args.some(
        (a) => a === "-i" || /^-i\S*$/.test(a) || a === "--in-place",
      );
      if (!inPlace) break;
      const rest = operands(SED_TAKES_A_VALUE);
      // With -e/-f the script is attached to the flag, so every operand is a file.
      // Otherwise the first operand IS the script — dropping it is what stops the guard
      // reporting `s/a/b/` as a filename.
      const scriptIsAttached = args.some(
        (a) => SED_TAKES_A_VALUE.has(a) || /^(-e|-f)\S/.test(a),
      );
      targets.push(...(scriptIsAttached ? rest : rest.slice(1)));
      break;
    }
    case "tee":
      targets.push(...operands());
      break;
    case "cp":
    case "mv":
    case "rsync": {
      // The last operand is the destination; the others are sources being read.
      const rest = operands(new Set(["-t", "--target-directory"]));
      // `-t DIR src...` inverts it: the flag carries the destination.
      const t = args.findIndex((a) => a === "-t" || a === "--target-directory");
      if (t !== -1 && args[t + 1]) targets.push(args[t + 1]);
      else if (rest.length >= 2) targets.push(rest[rest.length - 1]);
      break;
    }
    case "dd":
      for (const a of args) if (a.startsWith("of=")) targets.push(a.slice(3));
      break;
    case "truncate":
      targets.push(...operands(new Set(["-s", "--size", "-r", "--reference"])));
      break;
    default:
      break;
  }

  return targets.filter((t) => t && t !== "/dev/null" && !t.startsWith("&"));
}
